name: mooClouds
author: SantEnnio
category: Interface
tags: [Fx.morph, dynamic elements]
docs: http://eqepa.com/en/projects/mootools-plugins/mooclouds/
demo: http://eqepa.com/Playground/Mootools/mooClouds/Example/demo.html
current: 0.5