name: mooClouds
author: SantEnnio
category: Interface
tags: [Fx.morph, dynamic elements]
docs: http://www.enniopirolo.name/projects/mootools-projects/mooclouds/
demo: http://enniopirolo.name/demos/mooclouds/Example/demo.html
current: 0.8